"""Add one_off_items table

Revision ID: 1bb82be1a573
Revises: 87e72405688f
Create Date: 2025-08-20 22:55:43.389357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb82be1a573'
down_revision = '87e72405688f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###