"""add currency field to company

Revision ID: 1ca331332d1a
Revises: af74b85807d6
Create Date: 2025-08-21 16:47:00.553457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca331332d1a'
down_revision = 'af74b85807d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('currency', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'currency')
    # ### end Alembic commands ###