"""add multi bank account system

Revision ID: 2b9433948c58
Revises: 1ca331332d1a
Create Date: 2025-08-21 17:26:14.704663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9433948c58'
down_revision = '1ca331332d1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_id'), 'bank_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_bank_accounts_name'), 'bank_accounts', ['name'], unique=False)
    
    # Add bank_account_id columns (SQLite doesn't support adding foreign key constraints to existing tables)
    op.add_column('cash_flow_projections', sa.Column('bank_account_id', sa.Integer(), nullable=True))
    op.add_column('one_off_items', sa.Column('bank_account_id', sa.Integer(), nullable=True))
    op.add_column('recurring_expenses', sa.Column('bank_account_id', sa.Integer(), nullable=True))
    op.add_column('recurring_income', sa.Column('bank_account_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop bank_account_id columns
    op.drop_column('recurring_income', 'bank_account_id')
    op.drop_column('recurring_expenses', 'bank_account_id')
    op.drop_column('one_off_items', 'bank_account_id')
    op.drop_column('cash_flow_projections', 'bank_account_id')
    
    # Drop bank_accounts table
    op.drop_index(op.f('ix_bank_accounts_name'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###