"""Create one_off_items table properly

Revision ID: 48344341277c
Revises: 1bb82be1a573
Create Date: 2025-08-20 23:02:05.321806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48344341277c'
down_revision = '1bb82be1a573'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('one_off_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('item_type', sa.Enum('INCOME', 'EXPENSE', name='itemtype'), nullable=False),
    sa.Column('planned_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_confirmed', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_one_off_items_id'), 'one_off_items', ['id'], unique=False)
    op.create_index(op.f('ix_one_off_items_name'), 'one_off_items', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_one_off_items_name'), table_name='one_off_items')
    op.drop_index(op.f('ix_one_off_items_id'), table_name='one_off_items')
    op.drop_table('one_off_items')
    # ### end Alembic commands ###