"""Update one_off_items item_type to string

Revision ID: 5bcdbd40bfc1
Revises: 48344341277c
Create Date: 2025-08-20 23:03:28.230131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bcdbd40bfc1'
down_revision = '48344341277c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###