"""add customer business fields

Revision ID: 611557a68589
Revises: 5bcdbd40bfc1
Create Date: 2025-08-21 15:19:30.854990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611557a68589'
down_revision = '5bcdbd40bfc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###