"""add_bank_account_to_projection_items

Revision ID: 7a37d758645b
Revises: 2b9433948c58
Create Date: 2025-08-21 22:07:31.611091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a37d758645b'
down_revision = '2b9433948c58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support adding foreign key constraints to existing tables
    # Only add the missing column
    op.add_column('projection_items', sa.Column('bank_account_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projection_items', 'bank_account_id')
    # ### end Alembic commands ###