"""add customer business fields properly

Revision ID: af74b85807d6
Revises: 611557a68589
Create Date: 2025-08-21 15:25:48.322661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af74b85807d6'
down_revision = '611557a68589'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('product_type', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('revenue_model', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('partner', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('contract_start', sa.Date(), nullable=True))
    op.create_index(op.f('ix_customers_company_name'), 'customers', ['company_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_company_name'), table_name='customers')
    op.drop_column('customers', 'contract_start')
    op.drop_column('customers', 'partner')
    op.drop_column('customers', 'revenue_model')
    op.drop_column('customers', 'product_type')
    op.drop_column('customers', 'company_name')
    # ### end Alembic commands ###